[project]
name = "marketplace-sever"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "fastapi==0.116.1",
    "uvicorn",
    "pymongo==4.14.1",
    "email-validator==2.2.0",
    "certifi==2025.8.3",
    "rfc5424-logging-handler"
]
